# site.yml
---
# Best practise for ansible foreskriver at site.yml bruges til at includere de andre playbooks
- import_playbook: core.yml
- import_playbook: icinga2.yml
- import_playbook: mysql.yml
- import_playbook: web.yml
- import_playbook: haproxy.yml
