---
- web:
    - name: "site3"
      titel: "Site 3 titel custom"
      repo: https://github.com/mrscherrycoke/homepage101.git
      domains:
        - site3.customer.vagrant.101.dk
- mysql:
   - username: "site3"
     password: Site3Password
     database: "site3"
