---
- name: Sikre at  php7.2 og phpog php7.2 pakker er installeret
  apt:
    pkg:
      - php7.2
      - php7.2-fpm
      - php7.2-cli
      - php7.2-mysql
      - php7.2-curl
      - php7.2-gd
      - php7.2-json
      - php7.2-curl
      - php7.2-mbstring
      - php7.2-intl
      - php7.2-xml
      - php7.2-zip
      - php7.2-bz2
      - php-imagick
    state: present
  tags:
    - web
    - php
